print("hello world")
name="Japhet"
hobby="coding"
hours=4
print(F"my name is {name} i love {hobby} and i code {hours} hours a each day")
a=5 
b=4 
c="6" 
c=int("6")
print(a+b+c)
print(c*b)
print(a)
a= 2
b= "ama"
c= "john"
d= 0.564
print(type(a))
print(type(b))
print(type(c))
print(type(d))
a="i am happy learning software development"
b="i will finish in"
c=1 
d="year time"
print(a,b,c,d)